# Configuration

site_name: Information Retrieval for Experimaestro
site_description: experimaestro-ir Information Retrieval module for Experimaestro
repo_url: https://github.com/bpiwowar/experimaestro-ir

# Main pages
nav:
  - Home: index.md
  - Tasks and Configs: xpm.md

markdown_extensions:
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - admonition
  - pymdownx.snippets:
      base_path: .
  - toc:
      baselevel: 1

plugins:
  - experimaestro:
        path: xpm.md
        name: Tasks and configurations
        modules:
            - Experimaestro IR: experimaestro_ir

# Theme
theme:
    name: material
    feature:
        tabs: true
    palette:
        primary: 'indigo'
        accent: 'indigo'
    font:
        text: 'Roboto'
        code: 'Roboto Mono'
